name = "flavorlenstest1"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "flavorlens.de", custom_domain = true },
  { pattern = "www.flavorlens.de", custom_domain = true }
]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
